### ISSUE TITLE
Delay skifting between status Q and T

### ISSUE THREAD

**Issue by Hakansv** [douwefokkema/marpa#2]
For a new target:
First use status Q as it does. Then wait some additional seconds  to change to status T. I believe the Kalman filter may need more time to stabilize. For the first seconds the course and speed are like flapping around.

**Comment by douwefokkema** [comment]
Can be adjusted in the RadarMarpa.h file:
#define Q_NUM (3)      // status Q to OCPN at target status 3
#define T_NUM (7)      // status T to OCPN at target status 7

**Comment by Hakansv** [comment]
Due to the simulation I think these settings will do?
-#define Q_NUM (3)  // status Q to OCPN at target status 3
-#define T_NUM (7)  // status T to OCPN at target status 7
+#define Q_NUM (2)  // status Q to OCPN at target status 3
+#define T_NUM (5)  // status T to OCPN at target status 7
Maybe what is was before --- or :)

**Comment by douwefokkema** [comment]
Implemented commit 24-11-2016
