### ISSUE TITLE
Make a function for MARPA target deletion. 

### ISSUE THREAD

**Issue by Hakansv** [douwefokkema/marpa#4]
Now we can set and initiate a MARPA target on screen. I think a delete function is needed as well. Not less if I have set a target by mistake .

**Comment by douwefokkema** [comment]
Implemented in marpa3 efc38420150.
But, to delete a target do not click on the target (you will get the AIS menu), but close to the target to get the OCPN context menu. Not so nice, but how to change the AIS menu?

**Comment by Hakansv** [comment]
I've recently worked on the AIS-menu.  See: http://www.cruisersforum.com/forums/f134/mmsi-properties-175850-2.html#post2262267 , there's a link to my source as well.) So if you like I can see if there is something to find. For example if the target is of type ARPA then show "Delete ARPA target?? But you've already succeed to enter in to the OCPN main menu so it would not be that hard, would it?

**Comment by Hakansv** [comment]
As far as I can follow the code in O_canvasMenu.cpp the menu items from pluginmanager are added to the mase menu container before the AIS menu parts are separated. And there is no prepared way to sort plugin menus into any other menu group then the "contextMenu". I think if we would like append into the "menuAIS" group there has to changes to OCPN. But that's may be doable? 
Now----
We could continue is it is and add a new plugin menu mi5 and accept it will be in the context menu. But, we could maybe activate it only if a MARPA target is active?
OR
We could ask for help? to get it into the menuAIS group in OCPN?

It's not very intuitive though to point beside a target to get correct menu. We would do more here wouldn't we, and let this issue be open so far.

**Comment by douwefokkema** [comment]
New implementation committed

**Comment by Hakansv** [comment]
Recent "Delete ARPA Target" is working great although the menu item is still in the canvas menu and not in the AIS targets menu.
I couldn't find a method to direct this menu item into the AIS menu using present tools in wxMenu. All available setters are already used for other purposes. So to be able to solve this issue I believe we have to rebuild OCPN canvas menu handler and that's to much for now.
Please close if you agree.
