### ISSUE TITLE
No CPA and TCPA from OCPN

### ISSUE THREAD

**Issue by douwefokkema** [douwefokkema/marpa#6]
OCNP does not yet give CPA, fields in the target overview are empty.

**Comment by Hakansv** [comment]
It's working for me, are you sure all your OCPN conditions are fulfilled? The target must point to a course leading to approach and should not be behind with less speed and maybe more. ![02_ais_list](https://cloud.githubusercontent.com/assets/7202854/20556623/4982425e-b168-11e6-8e3e-51ea0ae4fbbf.PNG)This image is while running branch marpa3
![marpa_cpa](https://cloud.githubusercontent.com/assets/7202854/20556534/da290a8c-b167-11e6-8898-b336dc9cf7cc.PNG)

**Comment by douwefokkema** [comment]
Very good, happily I was wrong. I tried again and it works.
