### ISSUE TITLE
OCPN Crash at target deletion

### ISSUE THREAD

**Issue by Hakansv** [douwefokkema/marpa#7]
Repeatable crash: (Today's Github fetch)
OCPN is crashing when I delete the first, and it's single, ARPA target in one program session. 
Only If:
No more targets has been initiated in this session. 

Not if:
Any other target has been initiated. When one or more targets has been set I can delete the first. No matter if the second or third is still present or deleted. So it's not simply about the last target in the array.

**Comment by Hakansv** [comment]
Note for info:
"Delete all ARPA Targets" doesn't have the issued problem

**Comment by douwefokkema** [comment]
Can not reproduce. Can you send me the log file?

**Comment by Hakansv** [comment]
Yes, I've the last version but now I can't either reproduce on any machine. This is after a couple of O restart. The config file would be involved, yes.  Let's call it simulation errors.
