### ISSUE TITLE
ARPA targets remains on screen if radar connection is broken

### ISSUE THREAD

**Issue by Hakansv** [douwefokkema/marpa#9]
If the radar connection is broken all ARPA targets are left on screen showing last speed and course.
The "Delete all ARPA Targets" is not functional. (And the menu items would be deleted as well ?)
The targets will eventually be deleted by OCPN AIS target time out but following our target lost logic they would have got status lost even on this occurrence.

**Comment by douwefokkema** [comment]
Targets are deleted after a waiting period of 5 seconds. If  the radar comes back with that time frame, targets might still be alive. See commit e02c70f5acd

**Comment by Hakansv** [comment]
Tested - OK
Thanks/Håkan
